apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: petclinic
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: petclinic
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
