apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: petclinic
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: petclinic
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
