apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: petclinic
  labels:
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/part-of: petclinic
spec:
  type: ClusterIP
  selector:
    app: zipkin
  ports:
    - port: 9411
      targetPort: 9411
      protocol: TCP
