apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: petclinic
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: petclinic
type: Opaque
stringData:
  password: petclinic
  database: petclinic
  username: petclinic
